name: Build iOS Mod
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geode-sdk/build-geode-mod@main
        with:
          target: iOS
          combine: true
